AWSTemplateFormatVersion: 2010-09-09
Description: ECS Cluster of GymManagement

Parameters:
  ProjectName:
    Description: Project Name
    Type: String

Resources:
  ConnectDynamoFargateTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: dynamo
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/test-dynamodb-connection'
          Cpu: 0
          PortMappings:
            - Name: dynamo-test
              ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
              AppProtocol: http
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/gym-management
              awslogs-create-group: true
              awslogs-region: ${AWS::Region}
              awslogs-stream-prefix: ecs
      Family: gym-management
      TaskRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/gym-management-ecs-task-role'
      ExecutionRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/gym-management-ecs-task-execution-role'
      NetworkMode: awsvpc
      Cpu: 1024
      Memory: 3072

  OccupancyStatusECSService:
    Type: 'AWS::ECS::Service'
    DependsOn: ConnectDynamoFargateTaskDefinition
    Properties:
      ServiceName: occupancy-status-ecs-service
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !ImportValue SgEcsSecurityGroup
          Subnets:
            - !ImportValue EcsPrivateSubnetAZ1
            - !ImportValue EcsPrivateSubnetAZ2
      # LoadBalancers:
      #   - ContainerName: first-run-task
      #     ContainerPort: 8080
      #     LoadBalancerName:
      #       Ref: AWS::NoValue
      #     TargetGroupArn:
      #       Ref: TargetGroup
