@startuml

left to right direction

entity 混雑状態 {
    + 混雑状態ID : PK
    --
    ジムID
    ユーザーID
    入場時刻
    退場時刻
}

entity 入退館履歴 {
    + 履歴ID : PK
    --
    ジムID
    ユーザーID
    入場時刻
    退場時刻
}

entity 予約 {
    + 予約ID : PK
    --
    ジムID
    機材ID
    ユーザーID
    開始日時
    終了日時
}

entity 店舗 {
    + ジムID : PK
    --
    店舗名
}

entity 機材 {
    + 機材管理番号 : PK
    --
    メーカー
    機材名
}

entity 店舗所有在庫 {
    + 在庫ID : PK
    --
    ジムID
    機材管理番号
    在庫
}

entity ユーザ {
    + ユーザーID : PK
    --
    ユーザー名
}

機材 "1" -- "*" 店舗所有在庫
店舗 "1" -- "*" 店舗所有在庫
店舗所有在庫 "1" -- "*" 予約
予約 "*" -- "1" ユーザ

@enduml