AWSTemplateFormatVersion: 2010-09-09
Description: ECS Cluster of GymManagement

Parameters:
  ProjectName:
    Description: Project Name
    Type: String

Resources:
  # Clusterとパラメーターグループとサブネットグループ
  RdsDbCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      AvailabilityZones:
        - !Select [0, !GetAZs '']
        - !Select [2, !GetAZs '']
      BackupRetentionPeriod: 7
      DBClusterIdentifier: !Sub '${ProjectName}-database'
      DBClusterParameterGroupName: !Sub '${ProjectName}-aurora-parameter-group'
      # Subnet group 作成する
      DatabaseName: gym_db
      DBSubnetGroupName: !Sub '${ProjectName}-aurora-subnet-group'
      Engine: 'aurora-mysql'
      Port: 3306
      MasterUsername: 'admin_user'
      MasterUserPassword: "{{resolve:ssm-secure:/database_pw}}"
      PreferredBackupWindow: '17:20-17:50'
      PreferredMaintenanceWindow: 'sun:15:00-sun:16:00'
      VpcSecurityGroupIds:
        - !ImportValue 'SgDbSecurityGroup'
      StorageEncrypted: true
      EnableIAMDatabaseAuthentication: false
      # 通常のAuroraかAurora Serverlessか選択可能
      EngineMode: 'provisioned'
      DeletionProtection: false
      EnableHttpEndpoint: false

  AuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'subnet group'
      DBSubnetGroupName: !Sub '${ProjectName}-aurora-subnet-group'
      SubnetIds:
        - !ImportValue DbPrivateSubnetAZ1
        - !ImportValue DbPrivateSubnetAZ2

  AuroraClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Aurora MySQL 8.0 cluster parameter group
      DBClusterParameterGroupName: !Sub '${ProjectName}-aurora-parameter-group'
      Family: aurora-mysql8.0
      Parameters:
        time_zone: Asia/Tokyo
        character_set_database: utf8mb4
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-aurora-cluster-param-group'

  DbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllowMajorVersionUpgrade: false
      # DBインスタンスの変更を即時反映させるかメンテナンスウィンドウ時に反映させるか
      ApplyImmediately: true
      AutoMinorVersionUpgrade: false
      # 自動バックアップの保持期間
      BackupRetentionPeriod: 0
      DBClusterIdentifier: !Ref RdsDbCluster
      DBInstanceClass: db.t3.medium
      DBInstanceIdentifier: !Sub '${ProjectName}-db-instance'
      DBSubnetGroupName: !Sub '${ProjectName}-aurora-subnet-group'
      DeleteAutomatedBackups: true
      Engine: aurora-mysql
      PreferredMaintenanceWindow: 'sun:17:00-sun:17:30'
      PubliclyAccessible: false
