AWSTemplateFormatVersion: 2010-09-09
Description: ECS Cluster of GymManagement

Parameters:
  ProjectName:
    Description: Project Name
    Type: String

Resources:
  # Clusterとパラメーターグループとサブネットグループ
  RdsDbCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      AvailabilityZones:
        - !Select [0, !GetAZs '']
        - !Select [2, !GetAZs '']
      BackupRetentionPeriod: 7
      DBClusterIdentifier: !Sub '${ProjectName}-database'
      DBClusterParameterGroupName: 'aurora-mysql8.0'
      # Subnet group 作成する
      DBSubnetGroupName: 'aurora-subnet-group'
      Engine: 'aurora-mysql'
      Port: 3306
      MasterUsername: 'admin_user'
      MasterUserPassword: "{{resolve:ssm-secure:/database_pw}}"
      PreferredBackupWindow: '17:20-17:50'
      PreferredMaintenanceWindow: 'sun:15:00-sun:16:00'
      VpcSecurityGroupIds:
        - !ImportValue 'SgDbSecurityGroup'
      StorageEncrypted: true
      EnableIAMDatabaseAuthentication: false
      # 通常のAuroraかAurora Serverlessか選択可能
      EngineMode: 'provisioned'
      DeletionProtection: false
      EnableHttpEndpoint: false

  AuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'subnet group'
      DBSubnetGroupName: !Sub '${ProjectName}-aurora-subnet-group'
      SubnetIds:
        - !ImportValue DbPrivateSubnetAZ1
        - !ImportValue DbPrivateSubnetAZ2

  DbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllowMajorVersionUpgrade: false
      # DBインスタンスの変更を即時反映させるかメンテナンスウィンドウ時に反映させるか
      ApplyImmediately: true
      AutomaticBackupReplicationRegion: !Sub ${AWS::Region}
      AutoMinorVersionUpgrade: false
      # 自動バックアップの保持期間
      BackupRetentionPeriod: 0
      DatabaseInsightsMode: standard
      DBClusterIdentifier: !Ref RdsDbCluster
      DBInstanceClass: db.t3.small
      DBInstanceIdentifier: !Sub '${ProjectName}-db-instance'
      DBSubnetGroupName: !Sub '${ProjectName}-aurora-subnet-group'
      DeleteAutomatedBackups: true
      DeletionProtection: false
      EnablePerformanceInsights: true
      Engine: aurora-mysql
      PerformanceInsightsRetentionPeriod: 7
      PreferredMaintenanceWindow: 'sun:17:00-sun:17:30'
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !ImportValue SgDbSecurityGroup
